# Generated by Django 4.0.4 on 2022-05-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0002_rename_event_link_organization_events_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiversityFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='code_of_conduct',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parentorganization',
            name='code_of_conduct',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='diversity_focus',
            field=models.ManyToManyField(related_name='parent_org_diversity_focus', to='org_pages.diversityfocus'),
        ),
        migrations.AddField(
            model_name='organization',
            name='technology_focus',
            field=models.ManyToManyField(related_name='parent_org_technology_focus', to='org_pages.technologyfocus'),
        ),
        migrations.AddField(
            model_name='parentorganization',
            name='diversity_focus',
            field=models.ManyToManyField(related_name='org_diversity_focus', to='org_pages.diversityfocus'),
        ),
        migrations.AddField(
            model_name='parentorganization',
            name='technology_focus',
            field=models.ManyToManyField(related_name='org_technology_focus', to='org_pages.technologyfocus'),
        ),
    ]
