# Generated by Django 4.0.4 on 2022-05-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentorganization',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
