# Generated by Django 4.0.4 on 2022-06-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='parent_organizations',
        ),
    ]
