# Generated by Django 4.0.4 on 2022-06-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_options_alter_customuser_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APIUser",
        ),
    ]
