# Generated by Django 4.0.4 on 2022-06-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_apiuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organizations',
        ),
    ]
