# Generated by Django 4.0.4 on 2022-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_handle',
            field=models.CharField(blank=True, help_text='Github Username Example: kjaymiller', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn URL Example: https://www.linkedin.com/in/kjaymiller', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Twitter Handle Example: @kjaymiller', max_length=50, null=True),
        ),
    ]
