# Generated by Django 4.0.4 on 2022-06-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_github_handle_customuser_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_handle',
            field=models.CharField(blank=True, help_text='(OPTIONAL) Github Username Example: kjaymiller', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='(OPTIONAL) LinkedIn URL Example: https://www.linkedin.com/in/kjaymiller', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='(OPTIONAL) Twitter Handle Example: @kjaymiller', max_length=50, null=True),
        ),
    ]
