# Generated by Django 4.0.4 on 2022-06-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_github_handle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='github_handle',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter_handle',
        ),
        migrations.AddField(
            model_name='customuser',
            name='github',
            field=models.CharField(blank=True, help_text='(OPTIONAL) Github Username Example: kjaymiller', max_length=200, null=True, verbose_name='Github Username'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, help_text='(OPTIONAL) LinkedIn URL Example: https://www.linkedin.com/in/kjaymiller', null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, help_text='(OPTIONAL) Twitter Handle Example: @kjaymiller', max_length=50, null=True, verbose_name='Twitter Username'),
        ),
    ]
