# Generated by Django 4.0.4 on 2022-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_github_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agrees_to_coc',
            field=models.BooleanField(default=False, verbose_name='I agree to the Code of Conduct'),
        ),
    ]
