# Generated by Django 4.0.4 on 2022-05-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiversityFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Diversity Focuses',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(blank=True, max_length=250)),
                ('base_query', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ('name', 'region', 'country'),
            },
        ),
        migrations.CreateModel(
            name='TechnologyFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Technology Focuses',
            },
        ),
        migrations.CreateModel(
            name='ParentOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('social_links', models.TextField(blank=True)),
                ('events_link', models.URLField(blank=True)),
                ('online_only', models.BooleanField(default=False)),
                ('code_of_conduct', models.URLField(blank=True)),
                ('diversity_focus', models.ManyToManyField(blank=True, related_name='org_diversity_focus', to='org_pages.diversityfocus')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_pages.location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_pages.parentorganization')),
                ('technology_focus', models.ManyToManyField(blank=True, related_name='org_technology_focus', to='org_pages.technologyfocus')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code_of_conduct', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('social_links', models.TextField(blank=True)),
                ('events_link', models.URLField(blank=True)),
                ('online_only', models.BooleanField(default=False)),
                ('diversity_focus', models.ManyToManyField(blank=True, related_name='parent_org_diversity_focus', to='org_pages.diversityfocus')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_pages.location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_pages.parentorganization')),
                ('technology_focus', models.ManyToManyField(blank=True, related_name='parent_org_technology_focus', to='org_pages.technologyfocus')),
            ],
        ),
    ]
