# Generated by Django 4.0.4 on 2022-05-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='event_link',
            new_name='events_link',
        ),
        migrations.RenameField(
            model_name='parentorganization',
            old_name='event_link',
            new_name='events_link',
        ),
    ]
