# Generated by Django 4.0.4 on 2022-05-27 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diversityfocus',
            name='parent_diversity_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_pages.diversityfocus'),
        ),
    ]
