# Generated by Django 4.0.4 on 2022-05-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0002_diversityfocus_parent_diversity_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diversityfocus',
            name='parent_diversity_focus',
        ),
        migrations.AddField(
            model_name='diversityfocus',
            name='parent_diversity_focus',
            field=models.ManyToManyField(blank=True, null=True, related_name='parent_diversity_focus', to='org_pages.diversityfocus'),
        ),
    ]
