# Generated by Django 4.0.4 on 2022-05-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0003_diversityfocus_technologyfocus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='diversity_focus',
            field=models.ManyToManyField(blank=True, related_name='parent_org_diversity_focus', to='org_pages.diversityfocus'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='technology_focus',
            field=models.ManyToManyField(blank=True, related_name='parent_org_technology_focus', to='org_pages.technologyfocus'),
        ),
        migrations.AlterField(
            model_name='parentorganization',
            name='diversity_focus',
            field=models.ManyToManyField(blank=True, related_name='org_diversity_focus', to='org_pages.diversityfocus'),
        ),
        migrations.AlterField(
            model_name='parentorganization',
            name='technology_focus',
            field=models.ManyToManyField(blank=True, related_name='org_technology_focus', to='org_pages.technologyfocus'),
        ),
    ]
