# Generated by Django 4.0.4 on 2022-06-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0005_diversityfocus_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('pk', 'name', 'region', 'country')},
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logos'),
        ),
        migrations.AddField(
            model_name='parentorganization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logos'),
        ),
    ]
