# Generated by Django 4.0.4 on 2022-05-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0006_parentorganization_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='base_query',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
