# Generated by Django 4.0.4 on 2022-06-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0007_location_latitude_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentorganization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logos/e114f664-f6b4-4c52-84c7-441252455d10/'),
        ),
    ]
