# Generated by Django 4.0.4 on 2022-06-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0007_alter_organization_options_organization_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
