# Generated by Django 4.0.4 on 2022-05-24 19:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0007_location_base_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_pages.location'),
        ),
        migrations.AlterField(
            model_name='parentorganization',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_pages.location'),
        ),
    ]
