# Generated by Django 4.0.4 on 2022-06-22 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_pages', '0008_organization_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
