# Generated by Django 4.0.4 on 2022-06-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0008_alter_parentorganization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentorganization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logos/9b93a20f-470d-4e20-b026-4d9c8a7c3453/'),
        ),
    ]
