# Generated by Django 4.0.4 on 2022-05-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0009_alter_organization_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diversityfocus',
            options={'verbose_name_plural': 'Diversity Focuses'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name', 'region', 'country')},
        ),
        migrations.AlterModelOptions(
            name='technologyfocus',
            options={'verbose_name_plural': 'Technology Focuses'},
        ),
    ]
