# Generated by Django 4.0.4 on 2022-06-22 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_pages', '0009_organization_organizers_alter_organization_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='job_board',
            field=models.URLField(blank=True, help_text='URL to the job board for the organization.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='paid',
            field=models.BooleanField(default=False, help_text='Do members have to pay for membership?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=False, help_text='Is this organization active? Inactive organizations will be marked and filtered out.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code_of_conduct',
            field=models.URLField(blank=True, help_text='URL to the code of conduct for the organization.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text="Description of the organization. This will appear on the organization's page."),
        ),
        migrations.AlterField(
            model_name='organization',
            name='diversity_focus',
            field=models.ManyToManyField(blank=True, help_text='Diversity focuses for the organization. Select as many as apply. The more specific the better. Examples: Black Women, LGBTQIA+', related_name='parent_org_diversity_focus', to='org_pages.diversityfocus'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='events_link',
            field=models.URLField(blank=True, help_text="URL to the organization's events page."),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='(ADMINS ONLY) Is this organization featured on the home page?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location of the organization. Format: city, Optional(state/region), country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_pages.location'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo of the organization. Will be displayed on the organization's page.", upload_to='media/logos'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Name of the organization.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='online_only',
            field=models.BooleanField(default=False, help_text='Is this organization only available online?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organizers',
            field=models.ManyToManyField(blank=True, help_text='Users who are organizers of this organization.', related_name='organizers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Is this organization a sub-organization of another org? NOTE:The Parent Org Must exist before this org can be created.', null=True, on_delete=django.db.models.deletion.CASCADE, to='org_pages.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='(ADMIN Only) Has this organization been reviewed?'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Slug will be generated automatically from the name of the organization.', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='social_links',
            field=models.TextField(blank=True, help_text='Social media links for the organization. Put each url on a new line.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='technology_focus',
            field=models.ManyToManyField(blank=True, help_text="Technology focuses for the organization. If your org doesn't focus on a particular tech topic, Leave Blank", related_name='parent_org_technology_focus', to='org_pages.technologyfocus'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, help_text="URL to the organization's website.", null=True),
        ),
    ]
