# Generated by Django 4.0.4 on 2022-06-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0010_organization_slug_parentorganization_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentorganization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logos/c1f5eaa0-f3fd-4e6a-9906-de0ed64ceb6e/'),
        ),
    ]
