# Generated by Django 4.0.4 on 2022-06-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0010_organization_job_board_organization_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this organization active? Inactive organizations will be marked and filtered out.'),
        ),
    ]
