# Generated by Django 4.0.4 on 2022-06-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0011_alter_parentorganization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentorganization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logos/7b8d9832-a27a-45fa-9d25-0e41100aa819/'),
        ),
    ]
