# Generated by Django 4.0.4 on 2022-06-27 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_pages', '0011_alter_organization_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code_of_conduct',
            field=models.URLField(blank=True, help_text='URL to the code of conduct for the organization.', verbose_name='Code of Conduct'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo of the organization. Will be displayed on the organization's page.", upload_to='media/logos/76ed4c5f-844b-4cd1-93f1-c949f2169efc/'),
        ),
        migrations.CreateModel(
            name='ViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.JSONField()),
                ('organization', models.ForeignKey(help_text='Organization accused of violation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_pages.organization')),
                ('user', models.ForeignKey(help_text='User who reported the violation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.JSONField()),
                ('organization', models.ForeignKey(help_text='Organization the edit should go to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='org_pages.organization')),
                ('user', models.ForeignKey(help_text='User who suggested the edit.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
