# Generated by Django 4.0.4 on 2022-06-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0012_alter_parentorganization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentorganization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logos/3f5860bd-53bc-4d92-8cf0-58f90adcb3cd/'),
        ),
    ]
