# Generated by Django 4.0.4 on 2022-06-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0013_alter_organization_logo_alter_violationreport_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo of the organization. Will be displayed on the organization's page.", upload_to='media/logos/b1a068e6-b3b2-44fe-84a2-b014a01f020a/'),
        ),
    ]
