# Generated by Django 4.0.4 on 2022-06-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0014_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentorganization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logos/e5e17bdd-921a-4090-95cd-40daefd79c91/'),
        ),
    ]
