# Generated by Django 4.0.4 on 2022-06-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0015_alter_parentorganization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='parentorganization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logos/87d066e5-fbc3-4771-ad71-948e6c1ebbe7/'),
        ),
    ]
