# Generated by Django 4.0.4 on 2022-06-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0016_alter_organization_logo_alter_organization_org_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='diversity_focus',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='technology_focus',
        ),
        migrations.AddField(
            model_name='organization',
            name='diversity',
            field=models.ManyToManyField(blank=True, help_text='Diversity focuses for the organization. Select as many as apply. The more specific the better. Examples: Black Women, LGBTQIA+', related_name='parent_org_diversity', to='org_pages.diversityfocus'),
        ),
        migrations.AddField(
            model_name='organization',
            name='technology',
            field=models.ManyToManyField(blank=True, help_text="Technology focuses for the organization. If your org doesn't focus on a particular tech topic, Leave Blank", related_name='parent_org_technology', to='org_pages.technologyfocus'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo of the organization. Will be displayed on the organization's page.", upload_to='media/logos/e2a95ed4-ec32-4f43-b31e-38a86e607b7e/'),
        ),
    ]
