# Generated by Django 4.0.4 on 2022-07-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0017_remove_organization_diversity_focus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='social_links',
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo of the organization. Will be displayed on the organization's page.", upload_to='media/logos/2f25d1f3-cd95-4816-8fa7-17d841f02441/'),
        ),
    ]
