# Generated by Django 4.0.4 on 2022-07-01 05:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0018_remove_organization_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='social_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, help_text='Social media links for the organization. Put each url on a new line.', size=None),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo of the organization. Will be displayed on the organization's page.", upload_to='media/logos/ed074ff8-188e-4a30-b73b-15d99988c888/'),
        ),
    ]
