# Generated by Django 4.0.4 on 2022-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0020_diversityfocus_other_names_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo of the organization. Will be displayed on the organization's page.", upload_to='media/logos/0c3a1969-e198-4895-a004-48dc2280c5cb/'),
        ),
    ]
