# Generated by Django 4.0.4 on 2022-07-01 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_pages', '0021_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologyfocus',
            options={'ordering': ['name'], 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AddField(
            model_name='technologyfocus',
            name='other_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo of the organization. Will be displayed on the organization's page.", upload_to='media/logos/740b1ee7-b3a2-406b-8322-9f571d9d413d/'),
        ),
    ]
